// DO NOT MODIFY! AUTO GENERATED BY igo v1.0.1 (https://github.com/rocketlaunchr/igo)
// Copyright 2019 PJ Engineering and Business Solutions Pty. Ltd. All rights reserved.

package dbq

import fordefer "github.com/rocketlaunchr/igo/stack"

import (
	"fmt"
	"reflect"
	"strings"
)

// Database is used to set the Database.
// Different databases have different syntax for placeholders etc.
type Database int

const (
	// MySQL database
	MySQL Database = 0
	// PostgreSQL database
	PostgreSQL Database = 1
)

// INSERT will generate a INSERT statement.
func INSERT(tableName string, columns []string, rows int, dbtype ...Database) string {
	return fmt.Sprintf("INSERT INTO %s ( %s ) VALUES %s", tableName, strings.Join(columns, ","), Ph(len(columns), rows, dbtype...))
}

// Ph generates the placeholders for SQL queries.
// For a bulk insert operation, rows is the number of rows you intend
// to insert, and columnsN is the number of fields per row.
func Ph(columnsN, rows int, dbtype ...Database) string {

	var typ Database
	if len(dbtype) > 0 {
		typ = dbtype[0]
	}

	if typ == MySQL {
		inner := "( " + strings.TrimSuffix(strings.Repeat("?,", columnsN), ",") + " ),"
		return strings.TrimSuffix(strings.Repeat(inner, rows), ",")
	}

	var singleValuesStr string

	varCount := 1
	QleQYhYzRyWJjPj := fordefer.NewStack(true)
	defer QleQYhYzRyWJjPj.Unwind()
	for i := 1; i <= rows; i++ {
		singleValuesStr = singleValuesStr + "("
		zpfRFEgmotaFetH := fordefer.NewStack(true)
		defer zpfRFEgmotaFetH.Unwind()
		for j := 1; j <= columnsN; j++ {
			singleValuesStr = singleValuesStr + fmt.Sprintf("$%d,", varCount)
			varCount++
			zpfRFEgmotaFetH.Unwind()
		}
		singleValuesStr = strings.TrimSuffix(singleValuesStr, ",") + "),"
		QleQYhYzRyWJjPj.Unwind()
	}

	return strings.TrimSuffix(singleValuesStr, ",")
}

func sliceConv(arg reflect.Value) []interface{} {
	out := []interface{}{}

	if arg.Kind() == reflect.Slice {
		sbZRjxAwnwekrBE := fordefer.NewStack(true)
		defer sbZRjxAwnwekrBE.Unwind()
		for i := 0; i < arg.Len(); i++ {
			out = append(out, sliceConv(reflect.ValueOf(arg.Index(i).Interface()))...)
			sbZRjxAwnwekrBE.Unwind()
		}
	} else {
		out = append(out, arg.Interface())
	}

	return out
}
