// DO NOT MODIFY! AUTO GENERATED BY igo v1.0.3 (https://github.com/rocketlaunchr/igo)

// Copyright 2019-20 PJ Engineering and Business Solutions Pty. Ltd. All rights reserved.

package dbq

import (
	"context"
	"database/sql"
	"reflect"
	"strings"

	"github.com/cenkalti/backoff/v4"
	// "gopkg.in/cenkalti/backoff.v4"
)

// MustE is a wrapper around the E function. It will panic upon encountering an error.
// This can erradicate boiler-plate error handing code.
func MustE(ctx context.Context, db ExecContexter, query string, options *Options, args ...interface{}) sql.Result {
	whTHct, cuAxhx := E(ctx, db, query, options, args...)
	if cuAxhx != nil {
		panic(cuAxhx)
	}
	return whTHct
}

// E is used for "Exec" queries such as insert, update and delete.
//
// args is a list of values to replace the placeholders in the query. When an arg is a slice, the values of the slice
// will automatically be flattened to a list of interface{}.
func E(ctx context.Context, db ExecContexter, query string, options *Options, args ...interface{}) (sql.Result, error) {
	if ctx == nil {
		ctx = context.Background()
	}

	for _, v := range args {
		if arg := reflect.ValueOf(v); arg.Kind() == reflect.Slice {
			args = FlattenArgs(args...)
			break
		}
	}

	if options == nil || options.RetryPolicy == nil {
		return db.ExecContext(ctx, query, args...)
	}

	o := *options
	o.RetryPolicy = backoff.WithContext(o.RetryPolicy, ctx)

	var res sql.Result

	operation := func() error {
		var err error
		res, err = db.ExecContext(ctx, query, args...)
		if err != nil {
			if err == sql.ErrTxDone || err == sql.ErrConnDone || (strings.Contains(err.Error(), "sql: expected") && strings.Contains(err.Error(), "arguments, got")) {
				return &backoff.PermanentError{err}
			}
			return err
		}
		return nil
	}

	err := backoff.Retry(operation, o.RetryPolicy)
	if err != nil {
		return nil, err
	}

	return res, nil
}
